.TH NOVACOIN.CONF "8" "April 2013" "novacoin.conf 3.19"
.SH NAME
novacoin.conf \- novacoin configuration file
.SH SYNOPSIS
All command-line options (except for '-datadir' and '-conf') may be specified in a configuration file, and all configuration file options may also be specified on the command line. Command-line options override values set in the configuration file.
.TP
The configuration file is a list of 'setting=value' pairs, one per line, with optional comments starting with