.TH NOVACOIND "7" "April 2013" "novacoind 3.19" 
.SH NAME
novacoind \- peer-to-peer network based digital currency
.SH SYNOPSIS
novacoin [options] <command> [params]  
.TP
novacoin [options] help <command> - Get help for a command
.SH DESCRIPTION
This  manual page documents the novacoind program. Novacoin is a peer-to-peer digital currency. Peer-to-peer (P2P) means that there is no central authority to issue new money or keep track of transactions. Instead, these tasks are managed c